# Generated by Django 4.1.3 on 2022-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('recipe', models.TextField(blank=True, null=True, verbose_name='Рецепт')),
                ('image', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Картинка')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('exists', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
                'ordering': ['name'],
            },
        ),
    ]
