# Generated by Django 4.1.3 on 2022-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoffe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffe',
            name='volume',
            field=models.IntegerField(blank=True, default=200, verbose_name='Объем'),
        ),
    ]
