# Generated by Django 4.1.3 on 2022-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoffe', '0002_coffe_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Картинка')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('exists', models.BooleanField(default=True)),
                ('coffe', models.ManyToManyField(related_name='ingridients', to='acoffe.coffe')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ['name'],
            },
        ),
    ]
